// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfLJE2IdxzA8fant2vd56-vZJtgJ8QLUQ',
    appId: '1:698538807790:web:3a222c89029497edde3eff',
    messagingSenderId: '698538807790',
    projectId: 'semesterproject-11249',
    authDomain: 'semesterproject-11249.firebaseapp.com',
    storageBucket: 'semesterproject-11249.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyButoC7-i1z59xDGIisyCbL_IkHjsNJG98',
    appId: '1:698538807790:android:fd72aba827470126de3eff',
    messagingSenderId: '698538807790',
    projectId: 'semesterproject-11249',
    storageBucket: 'semesterproject-11249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXFUf5RmWD_rZs0s_7_ucFm-BzWT6T1pA',
    appId: '1:698538807790:ios:a9a6669e8c88fbf1de3eff',
    messagingSenderId: '698538807790',
    projectId: 'semesterproject-11249',
    storageBucket: 'semesterproject-11249.appspot.com',
    iosClientId: '698538807790-qmet6hrjkjq2o6gug9f9u0f8bjcehtgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.semesterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXFUf5RmWD_rZs0s_7_ucFm-BzWT6T1pA',
    appId: '1:698538807790:ios:a9a6669e8c88fbf1de3eff',
    messagingSenderId: '698538807790',
    projectId: 'semesterproject-11249',
    storageBucket: 'semesterproject-11249.appspot.com',
    iosClientId: '698538807790-qmet6hrjkjq2o6gug9f9u0f8bjcehtgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.semesterproject',
  );
}
