// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17d4c3rc7sK-NdLlxDF9OG9YcSGnwO7k',
    appId: '1:873192726683:web:13c0f43d932d8f225a663e',
    messagingSenderId: '873192726683',
    projectId: 'semester-project-f7216',
    authDomain: 'semester-project-f7216.firebaseapp.com',
    storageBucket: 'semester-project-f7216.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd84rhAGQxSXskJM_njzzJL_0yvvlfCXM',
    appId: '1:873192726683:android:b41b15f244bcf6765a663e',
    messagingSenderId: '873192726683',
    projectId: 'semester-project-f7216',
    storageBucket: 'semester-project-f7216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvNIMK7UUYYe9loJ4XW3HKqS6w__no5Y',
    appId: '1:873192726683:ios:91648690ea82b22e5a663e',
    messagingSenderId: '873192726683',
    projectId: 'semester-project-f7216',
    storageBucket: 'semester-project-f7216.appspot.com',
    iosClientId: '873192726683-p14ve13r0f0uuooqjq2aki94ntm71ab4.apps.googleusercontent.com',
    iosBundleId: 'com.example.semesterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuvNIMK7UUYYe9loJ4XW3HKqS6w__no5Y',
    appId: '1:873192726683:ios:91648690ea82b22e5a663e',
    messagingSenderId: '873192726683',
    projectId: 'semester-project-f7216',
    storageBucket: 'semester-project-f7216.appspot.com',
    iosClientId: '873192726683-p14ve13r0f0uuooqjq2aki94ntm71ab4.apps.googleusercontent.com',
    iosBundleId: 'com.example.semesterproject',
  );
}
